name: inequality
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.8
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.1.3
  - powerlaw=1.4.6
  - scikit-learn=0.22.2
  - scipy=1.5.2